### ISSUE TITLE
Email for api v4 request not working

### ISSUE THREAD

**Issue by Hector47** [xee-lab/xeedev-issues#3]
Hello,
I try to contact you to request access to the v4 api by "api [at] xee.com"
unfortunately i receive an Delivery Status Notification (Failure) saying that I cannot send email to the api email.

**Comment by Hector47** [comment]
You can find bellow the email I receive as reply:
> We're writing to let you know that the group you tried to contact (api) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>   * You might have spelled or formatted the group name incorrectly.
>   * The owner of the group may have removed this group.
>   * You may need to join the group before receiving permission to post.
>   * This group may not be open to posting.
> 
>  If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/xee.com/bin/topic.py?topic=25838.
> 
>  Thanks,
> 
>  xee.com admins

**Comment by alexjomin** [comment]
Thank you @Hector47, I'll let you know when it will be fixed

**Comment by Hector47** [comment]
How can I ask for an api v4 access in the meantime ?

**Comment by alexjomin** [comment]
It's fixed. Let's continue by email to get an early access to the v4.
